### ISSUE TITLE
Loop starting image

### ISSUE THREAD

**Issue by krisrmgua** [OptimalBits/bull#1559]
## Description
Running this for the first time and it does not seem to start properly. Just goes into a restart loop with this only error outputted for logs
```
{"name":"bull-prom-metrics","hostname":"answers-bull-exporter-76776dc6cb-6njqp","pid":8,"level":50,"msg":"No clean exit after 5 seconds, force exit","time":"2019-11-13T20:23:48.853Z","v":0}
```

## Minimal, Working Test code to reproduce the issue.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: answers-bull-exporter
  labels:
    app: answers-bull-exporter
spec:
  selector:
    matchLabels:
      app: answers-bull-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: answers-bull-exporter
    spec:
      containers:
        - name: answers-bull-exporter
          image: uphabit/bull_exporter:latest
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          resources:
            requests:
              cpu: 100m
              memory: 128M
            limits:
              cpu: 200m
              memory: 512M
          env:
            - name: EXPORTER_REDIS_URL
              value: redis://my.redisserver.com:6379/0
            - name: EXPORTER_PREFIX
              value: assist-task-manager
            - name: EXPORTER_STAT_PREFIX
              value: assist-task-manager-stats
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            httpGet:
              path: /healthz
              port: 9538
---
apiVersion: v1
kind: Service
metadata:
  name: answers-bull-exporter
  labels:
    app: answers-bull-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9538
      targetPort: 9538
  selector:
    app: answers-bull-exporter
```

## Additional information
Any Idea what I maybe doing wrong here?
