### ISSUE TITLE
Sandboxed process could also respect `--inspect-brk`

### ISSUE THREAD

**Issue by jpettit** [OptimalBits/bull#1571]
## Description
In case anyone just lost hours of their life like I did...

`lib/process/child-pool.js` only respects the `--inspect` arg when spawning sandboxed child processes.  So, if you are using `--inspect-brk` like I was, you'll run into problems getting a standalone consumer node application to log appropriately from within a separate running docker container while debugging.

## Minimal, Working Test code to reproduce the issue.
*Docker/producer-image*
```
new Queue('foo', ...)
queue.add('named bar', ...)
```

*Docker/consumer-image*
```
new Queue('foo', ...)
queue.process('named bar', 5, 'path/to/processor.js')
```

*docker-debug-compose*
```
services:
  producer-app:
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - ".
    ports:
      - "9229:9229"
...
  consumer-app:
    # is the same as above
```

*VSCode launch.config*
```
# Use Docker: Attach to Node
```

When using the above sources as a rough guide, I would launch producer, consumer, and redis docker containers using docker-compose, connect the VSCode debugger to the producer and consumer, and only see activation event logs when I create a job.  The reason being is that the spawned sandbox processes would bind to `127.0.0.1` (the default) because `lib/process/child-pool.js` only looks for `--inspect` args.

I hope this saves someone else the ridiculous amount of hours I just lost.

## Solution
Switch from `--inspect-brk` to `--inspect`.  Event handlers now fire when remotely attaching the debugger to Bull running in Docker/node.
