### ISSUE TITLE
Bug: Bull fails to connect to redis in docker-compose

### ISSUE THREAD

**Issue by BogdanStanciu** [OptimalBits/bull#1838]
## Description
I have a backend develop with bull. Everything is inside a docker-compose. When start the docker with `docker-compose up`, bull can't connect to redis service and return a `ECONNREFUSED`, BUT if i create a connection with a simple: `const redis = new Redis('redis://${notifierConfig.host}:${notifierConfig.port}');` everything works fine. 

Return the error: 

```
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 6379
}
```
## Minimal, Working Test code to reproduce the issue.

**module.ts**
```
@Module({})
export class NotificationModule {
    static register(config: RedisOptions): DynamicModule {
        return {
            module: NotificationModule, 
            imports: [
                BullModule.registerQueueAsync({
                    name: 'notifications', 
                    useFactory: async (config: RedisOptions) => ({
                        createClient: ( (type, config) => {
                            return new Redis(`redis://${config.host}:${config.port}`);
                        }),
                        settings: {
                            maxStalledCount: 1,
                            lockDuration: 30000,
                            stalledInterval: 30000,
                        }
                    }),
                }),
            ],
            controllers: [NotificationController],
            exports: [NotificationService]
        }
    }
}
```
**docker-compose.yml**
```
version: '3.5'
services:
   cache:
        image: redis
        volumes:
            - /redis.conf:/redis.conf
        ports:
            - 6379:6379
        command:
            - redis-server
            - /redis.conf

    backend-notifier:
        image: registry.image
        restart: always
        links:
            - cache
        depends_on: 
            - cache
        volumes:
            - ./.env:/app/.env          
```
**.env**
```
REDIS_HOST=cache
REDIS_PORT=6379
```

## Bull version
 bull@3.16.0
