### ISSUE TITLE
how to automatically refresh and get new queues?

### ISSUE THREAD

**Issue by jonathan-chin** [OptimalBits/bull#2772]
I apologize if this is an uninformed question; I'm new to BullMQ and message queues in general.

I'm running Bull Board through docker; when it spins up, it grabs all the queues that are already in redis and can track jobs that go in and out.

however, while it is running, if I create a new queue, it doesn't show up in Bull Board. refreshing the page doesn't update the list either. it's only if I stop my docker containers and restart them do I get the new updated list.

should I be able to see new queues as they are added?

here's my docker yaml file:
```
version: '3.5'

services:
  mq_redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis_db_data:/data/mq_redis
    networks:
      - frg-network

  mq_bullboard:
    image: venatum/bull-board
    restart: always
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: mq_redis
      REDIS_PORT: 6379
#      REDIS_PASSWORD: example-password
#      REDIS_USE_TLS: 'false'
#      BULL_PREFIX: bull
    depends_on:
      - mq_redis
    networks:
      - frg-network

volumes:
  redis_db_data:
    external: false

networks:
  frg-network:
    driver: bridge
```
